name: latex_build

on: [push]
jobs:  
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: dissertation
    steps:
    - name: Pull changes
      uses: actions/checkout@v1
    - name: Install LaTeX dependencies
      run: |
        sudo apt update
        cat latex_dependencies.txt | xargs sudo apt install
        which pdflatex
    - name: Compile dissertation LaTeX file
      run: |
        pdflatex l4proj.tex
    - name: Upload dissertation artifact
      uses: actions/upload-artifact@master
      with:
        name: latest dissertation pdf
        path: l4proj.pdf

