name: latex_build

on: 
  push:
    branches:
      - master
      - dissertation

jobs:  
  build_latex:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull changes
      uses: actions/checkout@v1
    - name: Install LaTeX dependencies
      run: |
        cd dissertation
        cat latex_dependencies.txt | xargs sudo apt-get install
        which pdflatex
    - name: Compile dissertation LaTeX file
      run: |
        cd dissertation
        pdflatex l4proj.tex
    - name: Upload dissertation artifact
      uses: actions/upload-artifact@master
      with:
        name: latest dissertation pdf
        path: dissertation/l4proj.pdf

